name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy frontend to Vercel
        working-directory: frontend
        run: npx vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_5uKHIZCGE6Bka6MyS2wN0zd1
          VERCEL_PROJECT_ID: prj_s7w0CgxUzjbPHg78WEAvyh24kytR
